version: "3.8"

services:
    mysqlsrv:
        image: mysql:5.7
        container_name: mysqlcontainer
        restart: "always"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - 3306:3306
        volumes:
            - ./etc/volumes/mysql/data:/var/lib/mysql
            - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
        networks:
            - bosch-compose-network

    mysqladmin:
        image: adminer
        restart: "always"
        ports:
            - 8099:8080
        networks:
            - bosch-compose-network

networks:
    bosch-compose-network:
        driver: bridge

volumes:
  mysql_bosch_data:
    external: true
